package com.dinyairsadot.clearledger.ui.theme

import androidx.compose.ui.graphics.Color

// ── Light theme tokens ────────────────────────────────────────────────────────
val LightPrimary              = Color(0xFF4CAF50)
val LightOnPrimary            = Color(0xFFFFFFFF)
val LightPrimaryContainer     = Color(0xFFC8E6C9)
val LightOnPrimaryContainer   = Color(0xFF1B5E20)
val LightSecondary            = Color(0xFF558B2F)
val LightOnSecondary          = Color(0xFFFFFFFF)
val LightSecondaryContainer   = Color(0xFFDCEDC8)
val LightOnSecondaryContainer = Color(0xFF1B5E20)
val LightTertiary             = Color(0xFF00796B)
val LightOnTertiary           = Color(0xFFFFFFFF)
val LightTertiaryContainer    = Color(0xFFB2DFDB)
val LightOnTertiaryContainer  = Color(0xFF004D40)
val LightBackground           = Color(0xFFFFFFFF)
val LightOnBackground         = Color(0xFF1C1B1F)
val LightSurface              = Color(0xFFFFFFFF)
val LightOnSurface            = Color(0xFF1C1B1F)
val LightSurfaceContainerLowest  = Color(0xFFFFFFFF)
val LightSurfaceContainerLow     = Color(0xFFFAFAFA)
val LightSurfaceContainer        = Color(0xFFF5F5F5)
val LightSurfaceContainerHigh    = Color(0xFFF0F0F0)
val LightSurfaceContainerHighest = Color(0xFFEBEBEB)
val LightSurfaceVariant       = Color(0xFFF5F5F5)
val LightOnSurfaceVariant     = Color(0xFF49454F)
val LightOutline              = Color(0xFF79747E)
val LightOutlineVariant       = Color(0xFFCAC4D0)
val LightError                = Color(0xFFB3261E)
val LightOnError              = Color(0xFFFFFFFF)
val LightErrorContainer       = Color(0xFFF9DEDC)
val LightOnErrorContainer     = Color(0xFF410E0B)

// ── Dark theme tokens ─────────────────────────────────────────────────────────
val DarkPrimary               = Color(0xFF81C784)
val DarkOnPrimary             = Color(0xFF003910)
val DarkPrimaryContainer      = Color(0xFF1B5E20)
val DarkOnPrimaryContainer    = Color(0xFFC8E6C9)
val DarkSecondary             = Color(0xFFAED581)
val DarkOnSecondary           = Color(0xFF1B3A00)
val DarkSecondaryContainer    = Color(0xFF254D00)
val DarkOnSecondaryContainer  = Color(0xFFDCEDC8)
val DarkTertiary              = Color(0xFF4DB6AC)
val DarkOnTertiary            = Color(0xFF003731)
val DarkTertiaryContainer     = Color(0xFF004D40)
val DarkOnTertiaryContainer   = Color(0xFFB2DFDB)
val DarkBackground            = Color(0xFF121212)
val DarkOnBackground          = Color(0xFFE6E1E5)
val DarkSurface               = Color(0xFF1E1E1E)
val DarkOnSurface             = Color(0xFFE6E1E5)
val DarkSurfaceContainerLowest  = Color(0xFF0D0D0D)
val DarkSurfaceContainerLow     = Color(0xFF1A1A1A)
val DarkSurfaceContainer        = Color(0xFF232323)
val DarkSurfaceContainerHigh    = Color(0xFF2C2C2C)
val DarkSurfaceContainerHighest = Color(0xFF353535)
val DarkSurfaceVariant        = Color(0xFF2C2C2C)
val DarkOnSurfaceVariant      = Color(0xFFCAC4D0)
val DarkOutline               = Color(0xFF938F99)
val DarkOutlineVariant        = Color(0xFF49454F)
val DarkError                 = Color(0xFFF2B8B5)
val DarkOnError               = Color(0xFF601410)
val DarkErrorContainer        = Color(0xFF8C1D18)
val DarkOnErrorContainer      = Color(0xFFF9DEDC)
